test getting started canary

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -34,7 +34,7 @@ executors:
 
   macos-executor:
     macos:
-      xcode: 13.2.1
+      xcode: 13.3.1
     resource_class: large
 
   # For RN apps that need to be upgraded before using latest iOS/macOS
@@ -1192,7 +1192,12 @@ datastore_auth_scenarios: &datastore_auth_scenarios
 workflows:
   build_test_deploy:
     jobs:
-      - build
+      - build:
+          # TODO: remove after testing
+          filters:
+            branches:
+              ignore:
+                - test-getting-started-flow
       - integ_setup:
           filters:
             <<: *releasable_branches
@@ -1603,3 +1608,292 @@ workflows:
                 - release
           requires:
             - deploy
+  # Scheduled smoke test workflow
+  # Jobs are pulled from the getting-started-smoke-test inline orb defined below
+  canaries:
+    # triggers:
+    #   - schedule:
+    #       # cron: 0 12 * * 1,2,3,4,5 # noon GMT (5am PT) every weekday
+    #       cron: 40,45 * * * * # test schedule
+    #       # only adding `filters` here because it's required when using the `schedule` property
+    #       # in reality, the branch doesn't matter since we're installing amplify-js from NPM in this workflow
+    #       filters:
+    #         branches:
+    #           only:
+    #             - test-getting-started-flow
+    jobs:
+      ## Web
+      # React
+      - getting-started-smoke-test/web:
+          name: React - latest
+          npx-command: create-react-app
+          framework: react
+          main-file-path: src/App.js
+          build-dir: build
+      - getting-started-smoke-test/web:
+          name: React - next
+          npx-command: create-react-app@next
+          framework: react
+          main-file-path: src/App.js
+          build-dir: build
+      # Next
+      - getting-started-smoke-test/web:
+          name: Next.js - latest
+          npx-command: create-next-app
+          framework: nextjs
+          main-file-path: pages/_app.js
+          dev-start: dev
+          build-dir: build
+          ssr: true
+      - getting-started-smoke-test/web:
+          name: Next.js - next
+          npx-command: create-next-app@canary
+          framework: nextjs
+          main-file-path: pages/_app.js
+          dev-start: dev
+          build-dir: build
+          ssr: true
+      # Angular
+      - getting-started-smoke-test/web:
+          name: Angular - latest
+          npx-command: -p @angular/cli ng new --defaults true --force
+          framework: angular
+          main-file-path: src/main.ts
+          dev-port: 4200
+          build-dir: dist
+      - getting-started-smoke-test/web:
+          name: Angular - next
+          npx-command: -p @angular/cli@next ng new --defaults true --force
+          framework: angular
+          main-file-path: src/main.ts
+          dev-port: 4200
+          build-dir: dist
+      # Vue
+      - getting-started-smoke-test/web:
+          name: Vue - latest
+          npx-command: -p @vue/cli vue create --default --force --registry "https://registry.npmmirror.com" # npmmirror works better with vue create specifically in CCI
+          framework: vue
+          main-file-path: src/main.js
+          dev-start: serve
+          dev-port: 8080
+          build-dir: dist
+      - getting-started-smoke-test/web:
+          name: Vue - next
+          npx-command: -p @vue/cli@next vue create --default --force --registry "https://registry.npmmirror.com"
+          framework: vue
+          main-file-path: src/main.js
+          dev-start: serve
+          dev-port: 8080
+          build-dir: dist
+      ## Mobile
+      # RN CLI
+      - getting-started-smoke-test/rn-ios:
+          name: RN iOS - latest
+          framework: rn_ios
+          main-file-path: ./App.js
+      - getting-started-smoke-test/rn-android:
+          name: RN Android - latest
+          framework: rn_android
+          main-file-path: ./App.js
+      - getting-started-smoke-test/rn-ios:
+          name: RN iOS - next
+          framework: rn_ios
+          main-file-path: ./App.js
+          tag: next
+      - getting-started-smoke-test/rn-android:
+          name: RN Android - next
+          framework: rn_android
+          main-file-path: ./App.js
+          tag: next
+      # Expo
+      - getting-started-smoke-test/expo:
+          name: Expo - latest
+          framework: expo_ios
+          main-file-path: ./App.js
+      - getting-started-smoke-test/expo:
+          name: Expo - next
+          framework: expo_ios
+          main-file-path: ./App.js
+          tag: next
+
+# Start Canary Orb
+orbs:
+  getting-started-smoke-test:
+    executors:
+      web-executor:
+        docker:
+          - image: cimg/node:lts
+        resource_class: large
+
+      android-executor:
+        machine:
+          image: android:202102-01
+        resource_class: large
+
+    common_env_vars: &common_env_vars
+      environment:
+        IMPORT_STATEMENT: import {Logger} from 'aws-amplify';
+        LIBRARY_STATEMENT: Logger.LOG_LEVEL='DEBUG';
+        MAX_WAIT_ON_TIMEOUT: 180000 # 3 minutes; how long we wait for the build to succeed before failing the job
+
+    jobs:
+      web:
+        parameters:
+          framework:
+            type: string
+          npx-command:
+            type: string
+          npx-post:
+            type: string
+            default: ''
+          main-file-path:
+            type: string
+          dev-start:
+            type: string
+            default: start
+          dev-port:
+            type: integer
+            default: 3000
+          build-dir:
+            type: string
+          ssr:
+            type: boolean
+            default: false
+        executor: web-executor
+        <<: *common_env_vars
+        working_directory: ~/project/amplify-getting-started-<< parameters.framework >>
+        steps:
+          - run:
+              name: Scaffold App
+              command: cd ../ && npx -y << parameters.npx-command >> amplify-getting-started-<< parameters.framework >> << parameters.npx-post >>
+              no_output_timeout: 2m
+          - run:
+              name: Install AmplifyJS
+              command: npm i -S aws-amplify && npm i -g wait-on serve
+          - run:
+              name: Call Amplify library in code
+              command: |
+                echo "$IMPORT_STATEMENT" | cat - << parameters.main-file-path >> | tee << parameters.main-file-path >>
+                echo "$LIBRARY_STATEMENT" >> << parameters.main-file-path >>
+          - run:
+              name: Run in Dev Mode
+              command: npm run << parameters.dev-start >> & wait-on http://localhost:<< parameters.dev-port >> -t $MAX_WAIT_ON_TIMEOUT
+          - unless:
+              condition: << parameters.ssr >>
+              steps:
+                - run:
+                    name: Run in Prod Mode
+                    command: npm run build && (serve -n -s << parameters.build-dir >> -l 4000 & wait-on http://localhost:4000  -t $MAX_WAIT_ON_TIMEOUT)
+          - when:
+              condition: << parameters.ssr >>
+              steps:
+                - run:
+                    name: Run in Prod Mode
+                    command: npm run build && (npm start & wait-on http://localhost:3000  -t $MAX_WAIT_ON_TIMEOUT)
+
+      rn-ios:
+        parameters:
+          framework:
+            type: string
+          main-file-path:
+            type: string
+          tag:
+            type: string
+            default: latest
+          xcode-version:
+            type: string
+            default: 13.4.0
+        macos:
+          xcode: << parameters.xcode-version >>
+        resource_class: large
+        working_directory: ~/amplify_getting_started_<< parameters.framework >>
+        steps:
+          - run:
+              name: Scaffold App
+              command: cd ../ && rm -rf amplify_getting_started_<< parameters.framework >> && npx react-native@<< parameters.tag >> init amplify_getting_started_<< parameters.framework >>
+              no_output_timeout: 10m
+          - run:
+              name: Install Amplify dependencies
+              command: npm install aws-amplify aws-amplify-react-native amazon-cognito-identity-js @react-native-community/netinfo @react-native-async-storage/async-storage @react-native-picker/picker
+          - run:
+              name: Pod Install
+              command: npx pod-install
+          - run:
+              name: Call Amplify library in code
+              command: |
+                echo "$IMPORT_STATEMENT" | cat - << parameters.main-file-path >> | tee << parameters.main-file-path >>
+                echo "$LIBRARY_STATEMENT" >> << parameters.main-file-path >>
+          - run:
+              name: Start App
+              command: npm run ios
+
+      rn-android:
+        parameters:
+          framework:
+            type: string
+          main-file-path:
+            type: string
+          tag:
+            type: string
+            default: latest
+        executor: android-executor
+        working_directory: ~/amplify_getting_started_<< parameters.framework >>
+        steps:
+          - run:
+              name: Create avd
+              command: |
+                SYSTEM_IMAGES="system-images;android-29;default;x86"
+                sdkmanager "$SYSTEM_IMAGES"
+                echo "no" | avdmanager --verbose create avd -n test -k "$SYSTEM_IMAGES"
+          - run:
+              name: Scaffold App
+              command: cd ../ && rm -rf amplify_getting_started_<< parameters.framework >> && npx react-native@<< parameters.tag >> init amplify_getting_started_<< parameters.framework >>
+              no_output_timeout: 10m
+          - run:
+              name: Install Amplify dependencies
+              command: npm install aws-amplify aws-amplify-react-native amazon-cognito-identity-js @react-native-community/netinfo @react-native-async-storage/async-storage @react-native-picker/picker
+          - run:
+              name: Call Amplify library in code
+              command: |
+                echo "$IMPORT_STATEMENT" | cat - << parameters.main-file-path >> | tee << parameters.main-file-path >>
+                echo "$LIBRARY_STATEMENT" >> << parameters.main-file-path >>
+          - run:
+              background: true
+              command: xcrun simctl boot "iPhone 13" || true
+              name: Start iOS simulator (background)
+          - run:
+              name: Start App
+              command: npm run android
+
+      expo:
+        parameters:
+          framework:
+            type: string
+          main-file-path:
+            type: string
+          tag:
+            type: string
+            default: latest
+        executor: web-executor
+        <<: *common_env_vars
+        working_directory: ~/amplify_getting_started_<< parameters.framework >>
+        steps:
+          - run:
+              name: Install Expo
+              command: npm i -g expo-cli@<< parameters.tag >> wait-on
+          - run:
+              name: Scaffold App
+              command: cd ../ && rm -rf amplify_getting_started_<< parameters.framework >> && expo-cli init amplify_getting_started_<< parameters.framework >> --yes
+              no_output_timeout: 5m
+          - run:
+              name: Install Amplify dependencies
+              command: yarn add aws-amplify aws-amplify-react-native @react-native-community/netinfo @react-native-async-storage/async-storage @react-native-picker/picker
+          - run:
+              name: Call Amplify library in code
+              command: |
+                echo "$IMPORT_STATEMENT" | cat - << parameters.main-file-path >> | tee << parameters.main-file-path >>
+                echo "$LIBRARY_STATEMENT" >> << parameters.main-file-path >>
+          - run:
+              name: Start App
+              command: yarn web & wait-on http://localhost:19006  -t $MAX_WAIT_ON_TIMEOUT
+# End Canary Orb
