update release workflow to check for api docs updates

diff --git a/.github/workflows/callable-npm-publish-release.yml b/.github/workflows/callable-npm-publish-release.yml
--- a/.github/workflows/callable-npm-publish-release.yml
+++ b/.github/workflows/callable-npm-publish-release.yml
@@ -2,6 +2,9 @@ name: Release to npm and update repository
 
 on: workflow_call
 
+env:
+  API_FILE: 'docs/references.json'
+
 jobs:
   deploy-prep:
     name: Prepare for release
@@ -54,16 +57,33 @@ jobs:
           RELEASE_COMMIT_MESSAGE=$(git log -n 1 --skip 1 --pretty=oneline)
           if [[ $RELEASE_COMMIT_MESSAGE = *release\(required\)* ]]; then git tag -f required-release $PUBLISH_COMMIT_HASH; fi
 
-      # Generate and commit API docs JSON file
+      # Generate API docs JSON file
       - name: Update API documentation
         working-directory: ./amplify-js
         run: |
           yarn run docs
           git add ./docs/api/
+
+      # Check if the API Docs have been updated
+      - name: Check for updated api docs
+        id: api_docs_updated
+        run: |
+          if git diff --cached --quiet -- ${{ env.API_FILE }}; then
+            echo "API docs have not changed"
+            echo "updated=false" >> $GITHUB_OUTPUT
+          else
+            echo "updated=true" >> $GITHUB_OUTPUT
+            echo "API docs have been updated"
+          fi
+
+      # Commit docs changes
+      - name: Commit docs changes
+        run: |
           git commit -m "chore(release): update API docs [skip release]"
 
       # configure aws credentials
       - name: Configure AWS Credentials
+        if: steps.api_docs_updated.outputs.updated == 'true'
         uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
         with:
           role-to-assume: ${{ vars.DOCS_ROLE }}
@@ -71,6 +91,7 @@ jobs:
 
       # Read secrets from secrets manager
       - name: Read secrets from AWS Secrets Manager into environment variables
+        if: steps.api_docs_updated.outputs.updated == 'true'
         uses: aws-actions/aws-secretsmanager-get-secrets@ff26a0aa6bd4dd5e51326b5afb3f5f6874c958c7 # v2.0.3
         with:
           secret-ids: |
@@ -79,6 +100,7 @@ jobs:
 
       # Post dispatch action with docs repo
       - name: Fire event
+        if: steps.api_docs_updated.outputs.updated == 'true'
         run: |
           curl -L \
             -X POST \
@@ -87,6 +109,14 @@ jobs:
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/aws-amplify/docs/dispatches \
             -d '{"event_type":"update-references"}'
+
+      # Fail this step if api docs have not been updated but continue running the workflow
+      - name: API Docs not updated
+        if: steps.api_docs_updated.outputs.updated == 'false'
+        run: |
+          echo "API Docs Have not been updated if API changes have been made please verify they are in the release"
+          exit 1
+        continue-on-error: true
 
       - name: Push post release changes to the release branch
         working-directory: ./amplify-js
