ci: run flaky data e2es without retry

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -9,69 +9,72 @@ on: pull_request
 permissions: read-all
 
 jobs:
-  prebuild:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
-        with:
-          path: amplify-js
-      - name: Setup node and build the repository
-        uses: ./amplify-js/.github/actions/node-and-build
-        with:
-          is-prebuild: true
-  unit-tests:
-    needs:
-      - prebuild
-    uses: ./.github/workflows/callable-unit-tests.yml
-  bundle-size-tests:
-    needs: prebuild
-    uses: ./.github/workflows/callable-bundle-size-tests.yml
-  license-test:
-    needs: prebuild
-    uses: ./.github/workflows/callable-test-license.yml
-  github-actions-test:
-    needs: prebuild
-    uses: ./.github/workflows/callable-test-github-actions.yml
-  tsc-compliance-test:
-    needs: prebuild
-    uses: ./.github/workflows/callable-test-tsc-compliance.yml
-  dependency-review:
-    needs: prebuild
-    uses: ./.github/workflows/callable-dependency-review.yml
-  all-unit-tests-pass:
-    name: Unit and Bundle tests have passed
-    needs:
-      - unit-tests
-      - bundle-size-tests
-      - license-test
-      - github-actions-test
-      - tsc-compliance-test
-      - dependency-review
-    runs-on: ubuntu-latest
-    if: success() # only run when all checks have passed
-    # store success output flag for ci job
-    outputs:
-      success: ${{ steps.setoutput.outputs.success }}
-    steps:
-      - id: setoutput
-        run: echo "success=true" >> $GITHUB_OUTPUT
-  ci:
-    runs-on: ubuntu-latest
-    if: always() # always run, so we never skip the check
-    name: ci - Unit and Bundle tests have passed
-    needs: all-unit-tests-pass
-    env:
-      PASSED: ${{ needs.all-unit-tests-pass.outputs.success }}
-    steps:
-      # this job passes only when output of all-unit-tests-pass job is set
-      # in case at least one of the checks fails, all-unit-tests-pass is skipped
-      # and the output will not be set, which will then cause the ci job to fail
-      - run: |
-          if [[ $PASSED == "true" ]]; then
-          echo "All checks have passed"
-          exit 0
-          else
-          echo "One or more checks have failed"
-          exit 1
-          fi
+  e2e:
+    secrets: inherit
+    uses: ./.github/workflows/callable-release-verification.yml
+#   prebuild:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout repository
+#         uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
+#         with:
+#           path: amplify-js
+#       - name: Setup node and build the repository
+#         uses: ./amplify-js/.github/actions/node-and-build
+#         with:
+#           is-prebuild: true
+#   unit-tests:
+#     needs:
+#       - prebuild
+#     uses: ./.github/workflows/callable-unit-tests.yml
+#   bundle-size-tests:
+#     needs: prebuild
+#     uses: ./.github/workflows/callable-bundle-size-tests.yml
+#   license-test:
+#     needs: prebuild
+#     uses: ./.github/workflows/callable-test-license.yml
+#   github-actions-test:
+#     needs: prebuild
+#     uses: ./.github/workflows/callable-test-github-actions.yml
+#   tsc-compliance-test:
+#     needs: prebuild
+#     uses: ./.github/workflows/callable-test-tsc-compliance.yml
+#   dependency-review:
+#     needs: prebuild
+#     uses: ./.github/workflows/callable-dependency-review.yml
+#   all-unit-tests-pass:
+#     name: Unit and Bundle tests have passed
+#     needs:
+#       - unit-tests
+#       - bundle-size-tests
+#       - license-test
+#       - github-actions-test
+#       - tsc-compliance-test
+#       - dependency-review
+#     runs-on: ubuntu-latest
+#     if: success() # only run when all checks have passed
+#     # store success output flag for ci job
+#     outputs:
+#       success: ${{ steps.setoutput.outputs.success }}
+#     steps:
+#       - id: setoutput
+#         run: echo "success=true" >> $GITHUB_OUTPUT
+#   ci:
+#     runs-on: ubuntu-latest
+#     if: always() # always run, so we never skip the check
+#     name: ci - Unit and Bundle tests have passed
+#     needs: all-unit-tests-pass
+#     env:
+#       PASSED: ${{ needs.all-unit-tests-pass.outputs.success }}
+#     steps:
+#       # this job passes only when output of all-unit-tests-pass job is set
+#       # in case at least one of the checks fails, all-unit-tests-pass is skipped
+#       # and the output will not be set, which will then cause the ci job to fail
+#       - run: |
+#           if [[ $PASSED == "true" ]]; then
+#           echo "All checks have passed"
+#           exit 0
+#           else
+#           echo "One or more checks have failed"
+#           exit 1
+#           fi
