Update snyk-security.yml

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -20,19 +20,16 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - name: Set up Snyk CLI to check for security issues
-        # Snyk can be used to break the build when it detects security issues.
-        # In this case we want to upload the SAST issues to GitHub Code Scanning
         uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
       - name: Build
-        run: yarn install # || true
-        # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
-        # Use || true to not fail the pipeline
+        run: yarn install || true
+        # Using `|| true` to not fail the pipeline
       - name: Snyk test
         env:
           SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
         run: snyk test --sarif | tee snyk-code.sarif # || true
 
-        # Push the Snyk Code results into GitHub Code Scanning tab
+      # Push the Snyk Code results into GitHub Code Scanning tab
       - name: Upload result to GitHub Code Scanning
         uses: github/codeql-action/upload-sarif@v2
         with:
